//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gartenkraft_Admin.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class tblBilling_Information
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblBilling_Information()
        {
            this.tblSales_Invoice = new HashSet<tblSales_Invoice>();
        }
    
        public int billing_id { get; set; }
        [Required]
        [DisplayName("Custormer ID")]
        public string customer_id { get; set; }
        [Required]
        [DisplayName("Billing Address")]
        public string billing_address1 { get; set; }
        [DisplayFormat(ConvertEmptyStringToNull = true, NullDisplayText = "[Null]")]
        [DisplayName("Billing Address 2")]
        public string billing_address2 { get; set; }
        [Required]
        [DisplayName("City")]
        public string billing_city { get; set; }
        [Required]
        [DisplayName("State")]
        public string billing_state { get; set; }
        [Required]
        [DisplayName("Zip")]
        public string billing_zip { get; set; }
        [DisplayFormat(ConvertEmptyStringToNull = true, NullDisplayText = "[Null]")]
        [DisplayName("Four Digit Zip")]
        public string billing_zip4 { get; set; }
        [Required]
        [DisplayName("Country")]
        public string billing_country { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSales_Invoice> tblSales_Invoice { get; set; }
    }
}
