//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gartenkraft_Admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblProduct
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblProduct()
        {
            this.tblInventories = new HashSet<tblInventory>();
            this.tblLineitems = new HashSet<tblLineitem>();
            this.tblProduct_Image = new HashSet<tblProduct_Image>();
        }
    
        public int product_id { get; set; }
        public string product_name { get; set; }
        public string product_short_description { get; set; }
        public string product_long_description { get; set; }
        public decimal product_unit_cost { get; set; }
        public decimal product_unit_price { get; set; }
        public int product_category_id { get; set; }
        public int product_store_id { get; set; }
        public decimal product_weight { get; set; }
        public System.DateTime product_date_added { get; set; }
        public Nullable<int> product_image_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblInventory> tblInventories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblLineitem> tblLineitems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblProduct_Image> tblProduct_Image { get; set; }
        public virtual tblProduct_Category tblProduct_Category { get; set; }
        public virtual tblStore tblStore { get; set; }
    }
}
