//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gartenkraft_Admin.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class tblProduct_Line
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblProduct_Line()
        {
            this.tblProducts = new HashSet<tblProduct>();
            this.tblProduct_Category = new HashSet<tblProduct_Category>();
            this.tblProduct_Line_Image = new HashSet<tblProduct_Line_Image>();
        }
        [Required]
        [DisplayName("Line Item ID")]
        public int product_line_id { get; set; }
        [Required]
        [DisplayName("Product Name")]
        public string product_line_name { get; set; }
        [Required]
        [DisplayName("Date")]
        public System.DateTime date_added { get; set; }
        [Required]
        [DisplayName("Soft Delete")]
        public bool soft_delete { get; set; }
        [Required]
        [DisplayName("Visible")]
        public bool is_visible { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblProduct> tblProducts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblProduct_Category> tblProduct_Category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblProduct_Line_Image> tblProduct_Line_Image { get; set; }
    }
}
