//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gartenkraft_Admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSales_Invoice
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblSales_Invoice()
        {
            this.tblSales_Invoice_Lineitem = new HashSet<tblSales_Invoice_Lineitem>();
        }
    
        public int invoice_id { get; set; }
        public System.DateTime invoice_date { get; set; }
        public string customer_id { get; set; }
        public Nullable<int> billing_id { get; set; }
        public Nullable<int> shipping_id { get; set; }
    
        public virtual tblBilling_Information tblBilling_Information { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSales_Invoice_Lineitem> tblSales_Invoice_Lineitem { get; set; }
        public virtual tblShipping tblShipping { get; set; }
    }
}
