//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gartenkraft_Admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwCheckout
    {
        public string billing_address1 { get; set; }
        public string billing_address2 { get; set; }
        public string billing_city { get; set; }
        public string billing_state { get; set; }
        public string billing_zip { get; set; }
        public string billing_zip4 { get; set; }
        public string billing_country { get; set; }
        public string shipping_address1 { get; set; }
        public string shipping_address2 { get; set; }
        public string shipping_city { get; set; }
        public string shipping_state { get; set; }
        public string shipping_zip { get; set; }
        public string shipping_zip4 { get; set; }
        public string shipping_country { get; set; }
        public System.DateTime invoice_date { get; set; }
        public int invoice_id { get; set; }
    }
}
