//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gartenkraft_Admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwInvoice_Lineitem
    {
        public int lineitem_id { get; set; }
        public int invoice_id { get; set; }
        public int product_id { get; set; }
        public string product_name { get; set; }
        public string product_short_description { get; set; }
        public string product_long_description { get; set; }
        public bool is_custom_product { get; set; }
        public int category_id { get; set; }
        public string category_name { get; set; }
        public int product_line_id { get; set; }
        public string product_line_name { get; set; }
        public int option_id { get; set; }
        public string title { get; set; }
        public decimal weight { get; set; }
        public decimal unit_price { get; set; }
    }
}
