//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gartenkraft_Admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwProduct_Line
    {
        public int product_line_id { get; set; }
        public string product_line_name { get; set; }
        public bool is_visible { get; set; }
        public bool soft_delete { get; set; }
    }
}
