//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gartenkraft.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class gartenkraftModelEntities : DbContext
    {
        public gartenkraftModelEntities()
            : base("name=gartenkraftModelEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<tblBilling_Information> tblBilling_Information { get; set; }
        public virtual DbSet<tblInventory> tblInventories { get; set; }
        public virtual DbSet<tblInvoice> tblInvoices { get; set; }
        public virtual DbSet<tblLineitem> tblLineitems { get; set; }
        public virtual DbSet<tblOrder> tblOrders { get; set; }
        public virtual DbSet<tblProduct> tblProducts { get; set; }
        public virtual DbSet<tblProduct_Category> tblProduct_Category { get; set; }
        public virtual DbSet<tblProduct_Category_Image> tblProduct_Category_Image { get; set; }
        public virtual DbSet<tblProduct_Image> tblProduct_Image { get; set; }
        public virtual DbSet<tblShipping> tblShippings { get; set; }
        public virtual DbSet<tblStore> tblStores { get; set; }
    }
}
