//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gartenkraft.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblProduct_Category_Image
    {
        public int product_category_image_id { get; set; }
        public int product_category_id { get; set; }
        public string product_category_image_name { get; set; }
    
        public virtual tblProduct_Category tblProduct_Category { get; set; }
    }
}
