//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gartenkraft.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSales_Invoice_Lineitem
    {
        private vwProduct product;

        public int lineitem_id { get; set; }
        public int product_id { get; private set; }
        //public int lineitem_quantity
        //{
        //    get
        //    {
        //        return this.lineitem_quantity;
        //    }
        //    set
        //    {
        //        lineitem_quantity = value;
        //        SetLineTotal();
        //    }
        //}
        private int qty;
        public int lineitem_quantity
        {
            get
            {
                return this.qty;
            }
            set
            {
                this.qty = value;
                if (this.product != null)
                {
                    SetLineTotal();
                }
            }
        }
        public int invoice_id { get; set; }
        public decimal LineTotal { get; private set; }

        public void SetProduct(vwProduct p)
        {
            this.product = p;
            this.product_id = p.product_id;
        }

        public vwProduct GetProduct()
        {
            return this.product;
        }

        public void SetLineTotal()
        {
            this.LineTotal = this.product.product_unit_price * this.lineitem_quantity;
        }

        public virtual tblSales_Invoice tblSales_Invoice { get; set; }
    }
}
