//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gartenkraft.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwCheckout
    {
        public string chkBillingAddress1 { get; set; }
        public string chkBillingAddress2 { get; set; }
        public string chkBillingCIty { get; set; }
        public string chkBillingState { get; set; }
        public string chkBillingZip { get; set; }
        public string chkBillingZip4 { get; set; }
        public string chkBillingCountry { get; set; }
        public string chkShippingAddress1 { get; set; }
        public string chkShippingAddress2 { get; set; }
        public string chkShippingCity { get; set; }
        public string chkShippingState { get; set; }
        public string chkShippingZip { get; set; }
        public string chkShippingZip4 { get; set; }
        public string chkShippingCountry { get; set; }
        public System.DateTime chkInvoiceDate { get; set; }
        public int chkInvoiceID { get; set; }
    }
}
