//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gartenkraft.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwFeaturedProduct
    {
        public int feature_id { get; set; }
        public int product_id { get; set; }
        public string product_name { get; set; }
        public string product_short_description { get; set; }
        public string product_long_description { get; set; }
        public string category_name { get; set; }
        public string product_line_name { get; set; }
        public bool soft_delete { get; set; }
        public bool is_visible { get; set; }
        public bool is_custom_product { get; set; }
        public int product_line_id { get; set; }
        public int category_id { get; set; }
    }
}
