//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gartenkraft.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class vwInvoice_Lineitem
    {
        [Display(Name = "Quantity")]
        public int lineitem_quantity { get; set; }

        [Display(Name = "")]
        public int invoice_id { get; set; }

        [Display(Name = "Product Name")]
        public string product_name { get; set; }

        [Display(Name = "Short Description")]
        public string product_short_description { get; set; }

        [Display(Name = "Price")]
        [DisplayFormat(DataFormatString = "{0:C}")]
        public decimal product_unit_price { get; set; }

        [Display(Name = "Category")]
        public int product_category_id { get; set; }

        [Display(Name = "Line")]
        public int product_line_id { get; set; }

        [Display(Name = "Weight")]
        public decimal product_weight { get; set; }
    }
}
