//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gartenkraft.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwProduct_Option
    {
        public string title { get; set; }
        public decimal weight { get; set; }
        public decimal unit_price { get; set; }
        public int option_id { get; set; }
        public int product_id { get; set; }
    }
}
